# Generated by Django 3.1.1 on 2020-09-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120)),
                ('temp', models.FloatField()),
                ('weather_details', models.CharField(max_length=120)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Weather_details_by_users',
            },
        ),
    ]
